### ISSUE TITLE
Cannot control temperature with climate entities wich have preset_mode set to none

### ISSUE THREAD

**Issue by darootler** [daenny/climate_group#37]
Hi,

i just upgraded from Z-Wave (deprecated) to Z-Wave JS. I am able to set the temperature of all Devolo thermostats one by one but not the group. There is no input box for the temperature:

![image](https://user-images.githubusercontent.com/11849583/107891460-17450280-6f1f-11eb-8596-0933a7f85806.png)
![image](https://user-images.githubusercontent.com/11849583/107891584-e1ece480-6f1f-11eb-888b-088a2193e064.png)

I was able to do that with the old (deprecated) Z-Wave integration.

Any hints?

Regards
Richard

**Comment by darootler** [comment]
The problem is that with the new Z-Wave integration there is a new attribute "preset_mode". To workaround this issue i just set the "preset_mode" on all my thermostats to "home" and now the group is working again.

Maybe you could "fix" this on your code?

Regards
Richard

**Comment by darootler** [comment]
Sorry, the workaround does not seem to work after a restart of HA. The following error is logged:

{code}
2021-02-20 10:28:34 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.thermostate fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/climate_group/climate.py", line 311, in async_update
    self._preset = Counter(itertools.chain(all_presets)).most_common(1)[0][0]
  File "/usr/local/lib/python3.8/collections/__init__.py", line 552, in __init__
    self.update(iterable, **kwds)
  File "/usr/local/lib/python3.8/collections/__init__.py", line 637, in update
    _count_elements(self, iterable)
TypeError: unhashable type: 'NodeListClass'
{code}

But i think the problem has something to do with the preset_modes set to nothing.

Regards
Richard

**Comment by daenny** [comment]
It should be solved with latest version
