### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by giovi321** [daenny/climate_group#44]
I am running the last version of climate_group Home Assistant 2021.9.3 but I get an error:

`

Logger: homeassistant.components.websocket_api.http.connection
Source: components/homeassistant/__init__.py:171
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:16:15 PM (3 occurrences)
Last logged: 11:20:33 PM
[2825400672] The system cannot restart because the configuration is not valid: Platform error climate.climate_group - Integration 'climate_group' not found.

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 728, in admin_handler
    await result
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/homeassistant/__init__.py", line 171, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error climate.climate_group - Integration 'climate_group' not found.
`

Any idea?

**Comment by daenny** [comment]
Is it installed correctly? For me it still works.

**Comment by giovi321** [comment]
It is installed correctly but I never got it to work. Always the same problem. What version of hass are you running?

**Comment by cz8s** [comment]
Had a similar problem. I realized I first had to add the custom_component, then restart, and after that add the new group to configuration.yaml

**Comment by daenny** [comment]
No update for a long time. Other report it's working.
