### ISSUE TITLE
Question: which temperatur is shown?

### ISSUE THREAD

**Issue by adandl** [daenny/climate_group#9]
Hello!
The climate group is very useful - thank you very much.
Just one question - I have three thermostats which I have in one group.
of course they have little different readings.
Which actual temperatur is shown on the group element?
Thanks a lot!

Albert

**Comment by daenny** [comment]
The average temperature is shown.

**Comment by adandl** [comment]
Sorry - I was away during new year :).
Is it possible to change the interface to show the temperatur from only one instead?
I have a wall-mount device in the group which has it's own reading and that is the one I'd like to display

**Comment by daenny** [comment]
Yes this could be implemented. However I do not have the time to do this. 
You would need to add a configuration variable like: 
`display_value: average|entitiy_id`

**Comment by daenny** [comment]
I have made an initial (not tested) implementation here:
https://github.com/daenny/climate_group/pull/28

you have to add:
```yaml
master_device: entity
```
to your config

**Comment by bash-worth** [comment]
Thanks for this component, I'm trying to use master_device: but I'm getting the following error when I try to use the master-sync branch (with ha 2021.5.4):

Error while setting up climate_group platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/climate_group/climate.py", line 95, in async_setup_platform
    ClimateGroup(
  File "/config/custom_components/climate_group/climate.py", line 143, in __init__
    async_track_state_change(
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 222, in async_track_state_change
    return async_track_state_change_event(hass, entity_ids, state_change_listener)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 253, in async_track_state_change_event
    entity_callbacks = hass.data.setdefault(TRACK_STATE_CHANGE_CALLBACKS, {})
AttributeError: 'NoneType' object has no attribute 'data'
